spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jboot_jsi?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrival=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: jr2018
    password: jr2018
  jpa:
    hibernate:
      ddl-auto: create-drop